spring:
  datasource:
    url: jdbc:mariadb://mydb.cvk6mz430c7j.ap-northeast-2.rds.amazonaws.com/mydb?autoReconnect=true&useSSL=false&serverTimezone=UTC
    driverClassName: org.mariadb.jdbc.Driver
    username: mydb
    password: '!1qazsoftj'
mybatis:
  type-aliases-package: com.example.cheongsihaengbeach.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
server:
  port: 8080
  servlet:
    session:
      timeout: 24h
      cookie:
        max-age: 24h
